name = "bookmarks"
main = "build/worker/shim.mjs"
compatibility_date = "2023-02-28"

[vars]
DISCORD_APPLICATION_ID = "..."
DISCORD_PUBLIC_KEY = "..."
WORKERS_RS_VERSION = "0.0.13"

# secrets to be added with `wrangler secret put`:
# DISCORD_TOKEN: Discord bot account token
# REGISTRATION_TOKEN: (optional) arbitrary shared token used to register commands

[build]
command = "cargo install -q worker-build --version 0.0.9 && worker-build --release"
